Repository OZ-Coding-School/oz_02_collabo-003-BE, pull requests merged in 2024-06, with the labels that each got.

#75 [BE]Fix : prompt msg combine code
  admins/views.py
  gpt_prompts/serializers.py
  gpt_prompts/urls.py
  gpt_prompts/views.py
Labels: enhancement

#77 [BE] Fix prompt admin id issue
  gpt_prompts/migrations/0002_remove_gptprompt_admins_id_gptprompt_user_id.py
  gpt_prompts/models.py
Labels: enhancement

#78 [BE] Fix: gpt_prompt 테이블 재생성
  gpt_prompts/migrations/0001_initial.py
  gpt_prompts/migrations/0002_remove_gptprompt_admins_id_gptprompt_user_id.py
Labels: enhancement

#86 [BE] Fix: luck prompt last date update issue
  gpt_prompts/serializers.py
  gpt_prompts/views.py
Labels: enhancement

#96 [BE] Feat: push time update
  admin_settings/migrations/0002_alter_adminsetting_push_time_and_more.py
  admin_settings/models.py
  admin_settings/serializers.py
  admin_settings/views.py
  admins/views.py
Labels: good first issue

#100 [BE] Feat: term_date, term_time 수정 및 생성
  admin_settings/urls.py
  admin_settings/views.py
Labels: good first issue

#98 [Fix] 이메일 수신자 직접 입력에서 DB에 있는 관리자 이메일로 변경
  gpt_prompts/apps.py
  gpt_prompts/scheduler.py
Labels: enhancement

#102 [BE] Fix: scheduler-time DB에서 변수 가져오기
  gpt_prompts/apps.py
  gpt_prompts/views.py
Labels: enhancement

#103 [BE] Add: luck message working log save into db
  Kluck_config/settings.py
  gpt_prompts/scheduler.py
  gpt_prompts/views.py
  poetry.lock
Labels: good first issue

#105 [Fix] 오늘의 운세 3개로 받던 것 하나만 받기
  gpt_prompts/views.py
Labels: enhancement

#109 DB reset
  admin_settings/migrations/0001_initial.py
  admin_settings/migrations/0002_alter_adminsetting_push_time_and_more.py
  admins/migrations/0001_initial.py
  admins/migrations/0002_remove_kluck_admin_adms_id.py
  gpt_prompts/migrations/0001_initial.py
  luck_messages/migrations/0001_initial.py
Labels: good first issue

#110 DB reset try2
  Kluck_config/settings.py
  admin_settings/migrations/0001_initial.py
  admins/migrations/0001_initial.py
  gpt_prompts/migrations/0001_initial.py
  gpt_prompts/models.py
  gpt_prompts/views.py
  luck_messages/migrations/0001_initial.py
Labels: enhancement

#113 [BE] Add: period luck message
  admin_settings/views.py
  admins/views.py
  gpt_prompts/scheduler.py
  gpt_prompts/urls_gpt.py
  gpt_prompts/views.py
Labels: bug, enhancement, good first issue

#118 [BE] Add: admin page - main page - dash board data API GET
  gpt_prompts/apps.py
  gpt_prompts/scheduler.py
  luck_messages/urls_admin.py
  luck_messages/views.py
Labels: enhancement, good first issue

#124 [BE] Feat: luck date list
  luck_messages/serializers.py
  luck_messages/urls_admin.py
  luck_messages/views.py
Labels: good first issue

#130 [Feat] 비활성 디바이스 토큰 삭제
  kluck_notifications/apps.py
  kluck_notifications/migrations/0003_devicetoken_update_time.py
  kluck_notifications/migrations/0004_alter_devicetoken_unique_together.py
  kluck_notifications/migrations/0005_rename_update_time_devicetoken_update_date.py
  kluck_notifications/models.py
  kluck_notifications/push_scheduler.py
  kluck_notifications/views.py
Labels: enhancement

#131 [Feat] 푸시 스케줄러 및 디바이스 토큰 요청 API 로그 저장
  kluck_notifications/apps.py
  kluck_notifications/push_scheduler.py
  kluck_notifications/views.py
Labels: enhancement

#137 Ready()를 통해서 스케쥴러 로드시 경고문제, 스케쥴러 설정값:push, terms 변경시 스ì케쥴러 재등록
  Kluck_config/wsgi.py
  admin_settings/views.py
  gpt_prompts/apps.py
  gpt_prompts/scheduler.py
  kluck_notifications/apps.py
  kluck_notifications/push_scheduler.py
Labels: good first issue
